---
- name: Generate Role Documentation
  tags: [role_docs]
  template:
    src: "role_docs/main.j2"
    dest: "{{ role_path }}/doc/{{ item.name }}"
    mode: 0664
  delegate_to: localhost
  vars:
    doc_file: "{{ item.name }}"
    doc_keys: "{{ item.doc_keys }}"
  with_items: "{{ lookup('file', 'templates/role_docs/doc_files.yml') | from_yaml }}"
